/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

scala {
    version = "2.12.15"
}

dependencies {

    implementation("org.scala-lang:scala-library:2.12.15")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.scalatest:scalatest_2.12:3.2.10")
    testImplementation("org.scalatestplus:junit-4-13_2.12:3.2.9.0")

    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.12:2.0.1")
}

